---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ChenXingHua.
--- DateTime: 2019/1/5 17:00
---

ScrollOrientation ={
    HORIZONTAL = "HORIZONTAL",
    VERTICAL = "VERTICAL"
}

 ScrollDirection =
{
    NEXT = "NEXT",
    PREVIOUS = "PREVIOUS"
}