---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ChenXingHua.
--- DateTime: 2019/1/5 16:38
---
local UIRenderItem = class("UIRenderItem")

function UIRenderItem:ctor(itemObject)
    self.gameObject = itemObject.gameObject
    self.transform = itemObject.transform
    self._rectTransform =self.gameObject:GetComponent("RectTransform")
end

function UIRenderItem:SetIndex(number)
    self.Index = number
end

function UIRenderItem:SetPosition(pos)
    self._rectTransform.anchoredPosition = pos
end

function UIRenderItem:GetPosition()
    return self._rectTransform.anchoredPosition
end

function UIRenderItem:Destroy()

    GameObject.Destroy( self._rectTransform.gameObject)
    GameObject.Destroy( self.gameObject)

end

return UIRenderItem